Repository digital-preservation/droid, pull requests merged in 2020-02, with the labels that each got.

#376 fix: CLI can browse again folders recursively
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/NoProfileRunCommand.java
  droid-results/src/main/java/uk/gov/nationalarchives/droid/util/FileUtil.java
Labels: bug

#377 upd: signature files to latest DROID_SignatureFile_V96 and container-signature-20200121
  droid-binary/bin/Using sigtool.txt
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/DroidCommandLineTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/TestContexCleanup.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/ArcArchiveContentIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/ArchiveContainerTestHelper.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/BZip2ArchiveContentIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/GZipArchiveContentIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/RarArchiveContainerIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/SevenZipArchiveContainerIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/TarArchiveContentIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/WarcArchiveContentIdentifierTest.java
  droid-command-line/src/test/java/uk/gov/nationalarchives/droid/command/archive/ZipArchiveContentIdentifierTest.java
  droid-command-line/src/test/resources/signatures/DROID_SignatureFile_V96.xml
  droid-command-line/src/test/resources/signatures/container-signature-20170330.xml
  droid-command-line/src/test/resources/signatures/container-signature-20200121.xml
  droid-container/src/main/resources/container-signature-20170330.xml
  droid-container/src/main/resources/container-signature-20200121.xml
  droid-container/src/test/java/uk/gov/nationalarchives/droid/container/odf/OdfIdentifierTest.java
  droid-container/src/test/java/uk/gov/nationalarchives/droid/container/ole2/Ole2RootFileTest.java
  droid-container/src/test/resources/container-signature-20200121.xml
  droid-container/src/test/resources/container-signature.xml
  droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/config/DroidGlobalConfig.java
  droid-results/custom_home/container_sigs/container-signature-20170330.xml
  droid-results/custom_home/container_sigs/container-signature-20200121.xml
  droid-results/custom_home/signature_files/DROID_SignatureFile_V96.xml
  droid-results/src/main/resources/DROID_SignatureFile_V96.xml
  droid-results/src/main/resources/default_droid.properties
Labels: dependencies

#378 Fix skeleton issue
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/ArchiveContentIdentifier.java
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/Bzip2ArchiveContentIdentifier.java
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/IsoArchiveContainerIdentifier.java
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/RarArchiveContainerIdentifier.java
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/archive/SevenZipArchiveContainerIdentifier.java
  droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/archive/ArcArchiveHandler.java
  droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/BZipIdentificationRequest.java
  droid-core-interfaces/src/main/java/uk/gov/nationalarchives/droid/core/interfaces/resource/GZipIdentificationRequest.java
Labels: bug

#380 Removed the 2 test files that are identified as TROJAN
  droid-core/test-skeletons/fmt/fmt-640-signature-id-969.mpg
  droid-core/test-skeletons/fmt/fmt-649-signature-id-977.mpg
Labels: security

#381 upd documentation for new release
  droid-binary/bin/ChangeLog
  droid-help/src/main/resources/Web pages/Exporting profiles.html
  droid-help/src/main/resources/Web pages/FAQ.html
  droid-help/src/main/resources/Web pages/Information collected by DROID.html
  droid-help/src/main/resources/Web pages/Third-party components.html
  droid-help/src/main/resources/Web pages/Welcome to DROID.html
  droid-help/src/main/resources/Web pages/Whats New.html
Labels: dependencies

#391 minor fixes on GUI help: broken images and copyright year
  droid-help/src/main/resources/DROID6.jhp
  droid-help/src/main/resources/Images/Filter option selection.png
  droid-help/src/main/resources/Images/Filter selection.png
  droid-help/src/main/resources/Images/General.png
  droid-help/src/main/resources/Images/Profile Defaults.png
  droid-help/src/main/resources/Images/Profile paused.png
  droid-help/src/main/resources/Images/Profile running.png
  droid-help/src/main/resources/Images/Signature Updates.png
  droid-help/src/main/resources/Web pages/Change preferences.html
  droid-help/src/main/resources/Web pages/Explore the results.html
  droid-help/src/main/resources/Web pages/License.html
  droid-help/src/main/resources/Web pages/Running a profile.html
  droid-help/src/main/resources/Web pages/Third-party components.html
  droid-help/src/main/resources/map.xml
Labels: bug

#392 fix: processing of the quiet parameter on CLI
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/DroidCommandLine.java
  droid-command-line/src/main/java/uk/gov/nationalarchives/droid/command/action/CommandLineParam.java
Labels: bug

#393 fix export dialog
  droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/DroidMainFrame.java
  droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.form
  droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportDialog.java
  droid-swing-ui/src/main/java/uk/gov/nationalarchives/droid/gui/export/ExportProgressDialog.java
Labels: bug
