Repository digital-preservation/droid, pull requests merged in 2020-04, with the labels that each got.

#443 Add Code Coverage to the build
  .gitignore
  .travis.yml
  README.md
  droid-parent/pom.xml
  droid-results/pom.xml
Labels: enhancement

#444 Fix the Travis build status badge in README.md
  README.md
Labels: documentation

#447 fix: put back LF (unix) line separators in csv exports
  droid-export/src/main/java/uk/gov/nationalarchives/droid/export/CsvItemWriter.java
  droid-export/src/test/java/uk/gov/nationalarchives/droid/export/CsvItemWriterTest.java
Labels: bug

#450 upd: appveyor account in README
  README.md
Labels: documentation
